// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSimulationState():Promise<main.SimulationState>;

export function IsRunning():Promise<boolean>;

export function StartSimulation():Promise<void>;

export function StopSimulation():Promise<void>;
