// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSimulationState() {
  return window['go']['main']['App']['GetSimulationState']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function StartSimulation() {
  return window['go']['main']['App']['StartSimulation']();
}

export function StopSimulation() {
  return window['go']['main']['App']['StopSimulation']();
}
